### Registrar Usuario
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstname": "Juan",
    "lastname": "Perez",
    "username": "jperez",
    "email": "jperez@gmail.com",
    "password": "123456"
}