### Signup
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "firstname": "Brandon",
    "lastname": "Vargas",
    "username": "bvargas",
    "email": "bvargas95@gmail.com",
    "password": "123456"
}

### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "bvargas95@gmail.com",
    "password": "123456"
}

### Logout
GET http://localhost:3000/api/logout

### Protected Route with cookie configuration
GET http://localhost:3000/api/protected
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwidXNlcl9pZCI6IjY2NTc5YWE3NDEzNTExYjI0NDk0OThhYSIsImlhdCI6MTcxNzAxNzM4NTA5OCwiZXhwIjoxNzE3MDE3Njg1MDk4fQ.UAfNjBvtKuCsEXKkfgpBhIK_5bdw9xtKveOl0h9Caag; Max-Age=300; Path=/; Expires=Wed, 29 May 2024 23:55:38 GMT; HttpOnly; SameSite=Strict,refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsInVzZXJfaWQiOiI2NjU3OWFhNzQxMzUxMWIyNDQ5NDk4YWEiLCJpYXQiOjE3MTcwMjY2Mzg3NDQsImV4cCI6MTcxNzYzMTQzODc0NH0.x1XTJeLhvqNf2dk0SfGmeOhHQObh6zvRZwdS7tbVH68; Max-Age=604800; Path=/; Expires=Wed, 05 Jun 2024 23:50:38 GMT; HttpOnly; SameSite=Strict



