### Signup
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "firstname": "Brandon",
    "lastname": "Vargas",
    "username": "bvargas",
    "email": "bvargas95@gmail.com",
    "password": "123456"
}

### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "bvargas95@gmail.com",
    "password": "123456"
}

### Logout
GET http://localhost:3000/api/logout

### Protected Route with cookie configuration
GET http://localhost:3000/api/protected
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwidXNlcl9pZCI6IjY2NTc5YWE3NDEzNTExYjI0NDk0OThhYSIsImlhdCI6MTcxNzAyODA0MTU3NiwiZXhwIjoxNzE3MDI4MzQxNTc2fQ.jlJOhTau4Tlvbhg88jIIL4hsCgppVyqnoggZHAgVbzQ; Max-Age=300; Path=/; Expires=Thu, 30 May 2024 00:19:01 GMT; HttpOnly; SameSite=Strict,refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsInVzZXJfaWQiOiI2NjU3OWFhNzQxMzUxMWIyNDQ5NDk4YWEiLCJpYXQiOjE3MTcwMjgwNDE1NzgsImV4cCI6MTcxNzYzMjg0MTU3OH0.KMHZx8UTbbAr0oaBwz_pNEj4a62ND0JLgSLj44TuI7w; Max-Age=604800; Path=/; Expires=Thu, 06 Jun 2024 00:14:01 GMT; HttpOnly; SameSite=Strict



