### Signup
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "firstname": "Juan",
    "lastname": "Lopez",
    "username": "jlopez89",
    "email": "jlopez89@gmail.com",
    "password": "123456"
}